Implement addition
IIS-ZPI/ZPI2024_zaoczni_IMPAKT pull request #9
Opened 2024-11-25 21:11 UTC by hubert-cywka

2024-11-26 07:57 UTC, tirey93 requested changes
we will be doing it in DI, please accept my other PR first and then adjust

2024-11-26 08:07 UTC, hubert-cywka commented
> we will be doing it in DI, please accept my other PR first and then adjust

I don't see any other PR. I agree that DI is good thing, but... do we really need it in this app? We won't have any tests, we won't have any changing requirements, we won't need to change the behaviour of this app. IMHO that's overengineering.

2024-11-26 08:22 UTC, tirey93 commented
Here: https://github.com/IIS-ZPI/ZPI2024_zaoczni_IMPAKT/pull/10

2024-11-29 10:31 UTC, daopol approved these changes

2024-11-29 10:32 UTC, tirey93 approved these changes

2024-11-29 10:33 UTC, merged